# Generated by Django 3.2.5 on 2021-08-20 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
                ('notatki', models.TextField(blank=True, help_text='Istotne informacje dotyczące klienta', null=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.CreateModel(
            name='Moja_Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('nip', models.CharField(help_text='NIP w formacie PLXXXXXXXXXX', max_length=12)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Moja Firma',
            },
        ),
        migrations.CreateModel(
            name='Operacje_technologiczne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('symbol', models.CharField(help_text='Maksymalnie 3 znaki', max_length=3)),
                ('czas_przezbrajania', models.PositiveSmallIntegerField(default=0, help_text='Jednostka - godzina', verbose_name='Czas przezbrajania maszyny')),
            ],
            options={
                'verbose_name_plural': 'Operacje',
            },
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwisko', models.CharField(max_length=50)),
                ('imie', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=11, null=True)),
                ('aktywny', models.BooleanField(default=False)),
                ('rola', models.CharField(choices=[('PRO', 'Projektant'), ('KP', 'Kierownik Produkcji'), ('PP', 'Pracownik Produkcji'), ('MON', 'Montażysta'), ('KPR', 'Kierownik Projektu'), ('DYR', 'Dyrektor')], max_length=3)),
                ('data_dodania', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_zatrudnienia', models.DateField(blank=True, null=True)),
                ('data_zwolnienia', models.DateField(blank=True, null=True)),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('wynagrodzenie_netto', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bhp_wygasa', models.DateField(blank=True, null=True)),
                ('badania_wygasaja', models.DateField(blank=True, null=True)),
                ('viza_wygasa', models.DateField(blank=True, null=True)),
                ('narodowosc', models.CharField(choices=[('PL', 'Polskie'), ('UA', 'Ukraiśkie')], max_length=2, verbose_name='narodowość')),
                ('nr_paszportu', models.CharField(blank=True, help_text='W przypadku obcokrajowców', max_length=9, null=True, verbose_name='numer paszportu')),
                ('nr_dowodu', models.CharField(max_length=9, null=True, verbose_name='numer dowodu')),
                ('nr_telefonu', models.CharField(max_length=9, null=True, verbose_name='numer telefonu')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('notatki', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(default='/foto/default_foto.jpeg', upload_to='foto')),
            ],
            options={
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('notatki', models.TextField(blank=True, help_text='Ważne informacje dotyczące projeku', null=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('ostatnia_modyfikacja', models.DateField(auto_now=True)),
                ('klient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kadry.klient')),
                ('szef_projektu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kadry.pracownik', verbose_name='szef projektu')),
            ],
            options={
                'verbose_name_plural': 'Projekty',
            },
        ),
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('ostatnia_modyfikacja', models.DateField(auto_now=True)),
                ('nr_projektu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kadry.projekt')),
            ],
            options={
                'verbose_name_plural': 'Zlecenia',
            },
        ),
        migrations.CreateModel(
            name='Marszruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('operacja', models.ManyToManyField(to='kadry.Operacje_technologiczne')),
                ('zlecenie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kadry.zlecenie')),
            ],
            options={
                'verbose_name_plural': 'Marszruty',
            },
        ),
    ]
