# Generated by Django 3.2.5 on 2021-07-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pesel',
            field=models.CharField(max_length=11),
        ),
    ]
