# Generated by Django 3.2.5 on 2021-08-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadry', '0002_marszruta_czasy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marszruta',
            options={},
        ),
        migrations.RemoveField(
            model_name='marszruta',
            name='czasy',
        ),
    ]
