# Generated by Django 3.2.5 on 2021-08-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadry', '0003_auto_20210826_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marszruta',
            options={'verbose_name_plural': 'Marszruty'},
        ),
    ]
