# Generated by Django 3.2.5 on 2021-08-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadry', '0005_marszruta_czasy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marszruta',
            name='czasy',
        ),
    ]
