# Generated by Django 3.2.5 on 2021-08-30 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadry', '0006_remove_marszruta_czasy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Czasy_jednostkowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_jednostkowy', models.DecimalField(decimal_places=2, default=0, help_text='Czas jednostkowy podawany w godzinach', max_digits=3)),
                ('marszruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.marszruta')),
                ('operacja', models.ManyToManyField(to='kadry.Operacje_technologiczne')),
            ],
        ),
    ]
