# Generated by Django 3.2.5 on 2021-08-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadry', '0007_czasy_jednostkowe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='czasy_jednostkowe',
            options={'verbose_name_plural': 'Czasy jednostkowe'},
        ),
        migrations.AddField(
            model_name='projekt',
            name='wartosc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zlecenie',
            name='wartosc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
